### ISSUE TITLE
[REQUEST] AFK mode

### ISSUE THREAD

**Issue by Altarus94** [mwiemarc/wowclassic_tradeskillwhisperlookup#1]
Like the title said, make the addon active only if you're /AFK

+ make a second command, for when I'm active, for exemple

!enchant for when i'm afk. like how it work right now
!enchanting for when I'm active. After talking to a potential customer, I give him the command to let a customer browse my skills.

**Comment by mwiemarc** [comment]
i'm not sure what you exactly mean but if i get it right i'm asking why you need an extra command to talk to customers? why don't just chat with them or let them whisper you with they'r questions?
